### ISSUE TITLE
I want someone to make a decent README file for this repo.

### ISSUE THREAD

**Issue by SarthakRana** [SarthakRana/Drowsiness-Detection-using-Facial-Landmarks#2]
I'd like one of my university projects to have a .readme file.
This makes for a good first pull request for people doing Hacktoberfest.
Thanks and happy open source coding.

**Comment by mehta-raghav** [comment]
Hi. I would like to work on this issue! Can you provided some context regarding this project? Thanks

**Comment by Akshu-on-github** [comment]
I'll take this up!
Oh, pardon, seems like we sent it at the same time!

**Comment by SarthakRana** [comment]
Hi @AkshayaKulasekaran  I think it would be fair to give this to Raghav on a first come first serve basis. Thanks for considering.
